const mongoose = require('mongoose');
const validator = require('validator');

const appointmentInfo = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'user',
  },
  clientId: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'Clients',
  },
  appointmentReason: {
    type: String,
  },
  expectations: {
    type: String,
  },
  clinicGoals: [
    {
      type: String,
      enum: [
        'Decrease activity duration',
        'Decrease activity intensity',
        'Decrease body fat',
        'Decrease body weight',
        'Decrease calcium intake',
        'Decrease carbohydrates intake',
        'Decrease choline intake',
        'Decrease copper intake',
        'Decrease electrolytes intake',
        'Decrease energy expenditure',
        'Decrease energy intake',
        'Decrease fat intake',
        'Decrease fiber intake',
        'Decrease fluoride intake',
        'Decrease folic acid intake',
        'Decrease fruit intake',
        'Decrease iron intake',
        'Decrease liquids intake',
        'Decrease magnesium intake',
        'Decrease manganese intake',
        'Decrease muscle mass',
        'Decrease niacin intake',
        'Decrease pantothenic acid intake',
        'Decrease phosphorus intake',
        'Decrease potassium intake',
        'Decrease protein intake',
        'Decrease riboflavin intake',
        'Decrease selenium intake',
        'Decrease sodium intake',
        'Decrease thiamin intake',
        'Decrease vegetable intake',
        'Decrease vitamin A intake',
        'Decrease vitamin B12 intake',
        'Decrease vitamin B6 intake',
        'Decrease vitamin C intake',
        'Decrease vitamin D intake',
        'Decrease vitamin E intake',
        'Decrease vitamin K intake',
        'Decrease zinc intake',
        'Improve swallowing',
        'Increase activity duration',
        'Increase activity intensity',
        'Increase activity intensity',
        'Increase body fat',
        'Increase body weight',
        'Increase calcium intake',
        'Increase carbohydrates intake',
        'Increase choline intake',
        'Increase copper intake',
        'Increase electrolytes intake',
        'Increase energy expenditure',
        'Increase energy intake',
        'Increase fat intake',
        'Increase fiber intake',
        'Increase fluid intake',
        'Increase fluoride intake',
        'Increase folic acid intake',
        'Increase fruit intake',
        'Increase iron intake',
        'Increase magnesium intake',
        'Increase manganese intake',
        'Increase muscle mass',
        'Increase niacin intake',
        'Increase pantothenic acid intake',
        'Increase phosphorus intake',
        'Increase potassium intake',
        'Increase protein intake',
        'Increase riboflavin intake',
        'Increase selenium intake',
        'Increase sodium intake',
        'Increase thiamin intake',
        'Increase vegetable intake',
        'Increase vitamin A intake',
        'Increase vitamin B12 intake',
        'Increase vitamin B6 intake',
        'Increase vitamin C intake',
        'Increase vitamin D intake',
        'Increase vitamin E intake',
        'Increase vitamin K intake',
        'Increase zinc intake',
        'Maintain body weight',
      ],
    },
  ],
  clinicGoalsInfo: {
    type: String,
  },
  otherInfo: {
    type: String,
  },
});

module.exports = mongoose.model('AppointmentInformation', appointmentInfo);
